// <auto-generated />
namespace OpenQbit.TrackingManagement.DataAccess.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class setDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201707010812099_setDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
